Added Tests for Object Detection C APIs
tensorflow/tflite-support pull request #724
Opened 2021-12-07 14:29 UTC by priankakariatyml

2021-12-07 21:03 UTC, khanhlvg requested changes

2021-12-07 21:03 UTC, khanhlvg commented on tensorflow_lite_support/c/test/task/vision/object_detector_test.cc
> +
Can you add test for score threshold?

2021-12-08 04:32 UTC, lu-wang-g commented on tensorflow_lite_support/c/test/task/vision/object_detector_test.cc
> +                     float first_category_score, char* first_category_label) {
nit: bounding_box -> expected_bounding_box, first_category_score -> expected_first_score, first_category_label -> expected_first_label.

2021-12-08 04:32 UTC, lu-wang-g commented on tensorflow_lite_support/c/test/task/vision/object_detector_test.cc
> +  EXPECT_EQ(strcmp(detection.categories[0].label, first_category_label), 0);
EXPECT_THAT(detection.categories[0].label, StrEq(first_category_label));

2021-12-08 04:38 UTC, priankakariatyml commented on tensorflow_lite_support/c/test/task/vision/object_detector_test.cc
> +
Donee

2021-12-08 04:38 UTC, priankakariatyml commented on tensorflow_lite_support/c/test/task/vision/object_detector_test.cc
> +  EXPECT_EQ(strcmp(detection.categories[0].label, first_category_label), 0);
Fixed

2021-12-08 09:00 UTC, khanhlvg approved these changes

2021-12-08 21:57 UTC, merged