Added iOS Image Searcher Options and Helpers
tensorflow/tflite-support pull request #873
Opened 2022-08-17 13:51 UTC by priankakariatyml

Added Cpp Helpers for Base Options
Added Embedding Options and Cpp Helpers

2022-08-17 14:17 UTC, khanhlvg requested changes

2022-08-17 14:17 UTC, khanhlvg commented on tensorflow_lite_support/ios/task/core/sources/TFLBaseOptions+CppHelpers.h
> +- (void)copyTocppOptions:(tflite::task::core::BaseOptions *)cppOptions;
nit: copyToCppOptions for correct camel case.

2022-08-17 18:11 UTC, schmidt-sebastian approved these changes

2022-08-18 22:18 UTC, khanhlvg approved these changes

2022-08-22 17:44 UTC, merged