Added Image Searcher API Implementation and Basic Test
tensorflow/tflite-support pull request #887
Opened 2022-09-29 09:50 UTC by priankakariatyml

Added following files:
1. TFLSearch Result and helpers
2. TFLImageSearcher API Implementation
3. One Basic Objective C Test

2022-10-06 02:57 UTC, khanhlvg requested changes

2022-10-06 02:57 UTC, khanhlvg commented on tensorflow_lite_support/ios/task/processor/sources/TFLSearchResult.h
> +- (instancetype)initWithMetaData:(NSString *)metadata distance:(CGFloat)distance;
nit: `initWithMetadata` because metadata is a single word.

2022-10-06 02:57 UTC, khanhlvg commented on tensorflow_lite_support/ios/task/vision/sources/TFLImageSearcher.h
> +- (nullable TFLSearchResult *)searchInGMLImage:(GMLImage *)image
It should be `searchWithGMLImage`. "with" rather than "in" because we don't search in the image but find similar images in a pre-indexed database.

2022-10-06 02:57 UTC, khanhlvg commented on tensorflow_lite_support/ios/test/task/vision/image_searcher/TFLImageSearcherTests.m
> +  // Put setup code here. This method is called before the invocation of each test method in the
Please remove this comment.

2022-10-06 02:57 UTC, khanhlvg commented on tensorflow_lite_support/ios/test/task/vision/image_searcher/TFLImageSearcherTests.m
> +#define VerifySearchResult(searchResult, expectedNearestNeighborsCount) \
I think you should name it VerifySearchResultCount to be more precise.

2022-10-07 17:28 UTC, schmidt-sebastian commented on tensorflow_lite_support/ios/task/processor/sources/TFLSearchResult+Helpers.h
> + * Creates and retruns a TFLSearchResult from the result of search task returned by TFLite Task C++
Typo (will fix during import)

2022-10-07 17:29 UTC, schmidt-sebastian commented on tensorflow_lite_support/ios/task/vision/sources/TFLImageSearcher.h
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
2022 (will fix during import)

2022-10-07 17:32 UTC, schmidt-sebastian approved these changes

2022-10-07 17:32 UTC, schmidt-sebastian commented on tensorflow_lite_support/ios/task/vision/sources/TFLImageSearcher.h
> + * @discussion The external model file, must be a single standalone TFLite file. It could be packed
Drop comma (will fix during import)

2022-10-07 17:32 UTC, schmidt-sebastian commented on tensorflow_lite_support/ios/task/vision/sources/TFLImageSearcher.h
> + * with TFLite Model Metadata[1] and associated files if exist. Fail to provide the necessary
exists? and "Failure" (will fix during import)

2022-10-07 17:32 UTC, schmidt-sebastian commented on tensorflow_lite_support/ios/task/vision/sources/TFLImageSearcher.h
> + * @return An instance of `TFLImageSearcherOptions` initialized to the given
Fix line break (will fix during import)

2022-10-07 17:32 UTC, schmidt-sebastian commented on tensorflow_lite_support/ios/task/vision/sources/TFLImageSearcher.mm
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
2022 (will fix during import)

2022-10-07 17:32 UTC, schmidt-sebastian commented on tensorflow_lite_support/ios/test/task/vision/image_searcher/TFLImageSearcherTests.m
> +/* Copyright 2021 The TensorFlow Authors. All Rights Reserved.
2022 (will fix during import)

2022-10-10 22:47 UTC, merged