Added Image Segmenter Obj C Tests for More Scenarios
tensorflow/tflite-support pull request #891
Opened 2022-10-13 13:43 UTC by priankakariatyml

1. Fixed bug in error propagation when creating image segmenter.
2. Added method declaration for inference with roi.
3. Added more tests.

2022-10-13 13:46 UTC, priankakariatyml commented
@khanhlvg @schmidt-sebastian Raised a PR for more objc tests

2022-10-14 17:29 UTC, khanhlvg requested changes
Thanks Prianka! I have just one minor comment.

2022-10-14 17:29 UTC, khanhlvg commented on tensorflow_lite_support/ios/test/task/vision/image_searcher/TFLImageSearcherTests.m
> +                                       andIndexFileName:(nullable NSString *)indexFileName {
Remove "and" in method name as in Objective-C code convention.

2022-10-17 14:15 UTC, khanhlvg approved these changes

2022-10-18 17:59 UTC, khanhlvg commented
@schmidt-sebastian  The https://github.com/tensorflow/tflite-support/pull/891/commits/b7af86edcc1f8eb2ab37c3dc638bd430f5bb5762 commit was added after you imported the PR. Could you add it manually to your CL?

2022-10-20 03:01 UTC, khanhlvg commented
@priankakariatyml The PR has been merged in https://github.com/tensorflow/tflite-support/commit/949e3e4652a72f46c012ef4f508137ba7fa71b63. The last two commits can't be added to this PR. Can you pull master, patch the last two commits and send a new PR?

2022-10-20 03:01 UTC, closed without merging